# Generated by Django 2.0.6 on 2018-06-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Artist name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Music category name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Music title')),
                ('song', models.FileField(upload_to='media/songs/', verbose_name='MP3 audio sound')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos/', verbose_name='MP4 video song')),
                ('release_date', models.DateField(verbose_name='Release date')),
                ('num_stars', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, verbose_name='Number of stars')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.Artist', verbose_name='Song artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.Category', verbose_name='Music category')),
            ],
            options={
                'ordering': ['artist', 'title', 'song', 'release_date'],
            },
        ),
    ]
