# Generated by Django 2.0.6 on 2018-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='slug',
            field=models.SlugField(default='', max_length=60, verbose_name='Music slug'),
        ),
    ]
