# Generated by Django 2.0.6 on 2018-06-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_music_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='slug',
        ),
    ]
