# Generated by Django 2.0.6 on 2018-06-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_remove_music_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Number of stars'),
        ),
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.FileField(blank=True, upload_to='songs/', verbose_name='MP3 audio sound'),
        ),
        migrations.AlterField(
            model_name='music',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='videos/', verbose_name='MP4 video song'),
        ),
    ]
