# Generated by Django 2.0.6 on 2018-06-06 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name="Category's name")),
                ('date_created', models.DateField(default=datetime.date(2018, 6, 6), verbose_name='Date created')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='title of entry')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name="url's slug")),
                ('brief_content', models.TextField(default='', verbose_name='brief description of content')),
                ('content', models.TextField(verbose_name='entry content')),
                ('release_date', models.DateField(default=datetime.date(2018, 6, 6))),
                ('published', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='images/', verbose_name="entry's image")),
                ('tags', models.CharField(default='Article', max_length=50)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='article Category')),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name="person's'username'")),
                ('first_name', models.CharField(max_length=50, verbose_name="person's 'first name'")),
                ('last_name', models.CharField(max_length=50, verbose_name="person's 'last name'")),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Person', verbose_name='person publishing'),
        ),
    ]
