# Generated by Django 2.0.6 on 2018-06-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Event title')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Event slug')),
                ('content', models.TextField(verbose_name='Event content')),
                ('date', models.DateField(verbose_name='Event date')),
                ('published', models.BooleanField(verbose_name='Publish event ?')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
